name: Luxoria Desktop App Release

on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*
      - fix/ci/*

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, x86, arm64]

    env:
      Solution_Name: Luxoria.App.sln

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'  # Specify the .NET SDK version you are using
      
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      
      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}
        working-directory: ./Luxoria.App

      # Create the app by building and publishing the project
      - name: Build Luxoria.App
        run: msbuild $env:Solution_Name /t:Publish /p:Configuration=$env:Configuration /p:Platform=$env:Platform
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
        working-directory: ./Luxoria.App

      # Upload the app as an artifact
      - name: Upload Luxoria.App as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: Luxoria.App.${{ matrix.platform }}
          path: ./Luxoria.App/Luxoria.App/bin/
